import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-health-score',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
<div class="min-h-screen bg-slate-950 flex">
  <!-- Sidebar (mini) -->
  <aside class="w-64 bg-slate-900 border-r border-white/5 flex flex-col fixed h-full">
    <div class="p-6 border-b border-white/5">
      <div class="flex items-center gap-3">
        <div class="w-9 h-9 bg-blue-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/30">
          <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>
        </div>
        <h1 class="text-white font-bold text-sm">FinPulse AI</h1>
      </div>
    </div>
    <nav class="flex-1 p-4 space-y-1">
      <a routerLink="/dashboard" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-all text-sm">Overview</a>
      <a routerLink="/msme" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-all text-sm">MSME Profile</a>
      <a routerLink="/health-score" class="flex items-center gap-3 px-3 py-2.5 rounded-xl bg-blue-600/20 text-blue-400 border border-blue-500/30 transition-all text-sm font-semibold">Health Score</a>
      <a routerLink="/loan" class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-slate-400 hover:text-white hover:bg-white/5 transition-all text-sm">Loan Readiness</a>
    </nav>
  </aside>

  <main class="flex-1 ml-64 p-8">
    <div class="mb-8">
      <h2 class="text-2xl font-bold text-white">AI Financial Health Score</h2>
      <p class="text-slate-400 text-sm">Generated by our intelligent scoring engine</p>
    </div>

    <!-- Score Visualization -->
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-6 mb-8">
      <!-- Big Score Display -->
      <div class="bg-slate-900 border border-white/5 rounded-2xl p-8 flex flex-col items-center justify-center">
        <p class="text-slate-400 text-sm mb-4">Overall Credit Score</p>
        <!-- SVG Gauge -->
        <div class="relative w-48 h-48 mb-4">
          <svg viewBox="0 0 120 120" class="w-full h-full -rotate-90">
            <circle cx="60" cy="60" r="50" fill="none" stroke="#1e293b" stroke-width="12"/>
            <circle cx="60" cy="60" r="50" fill="none" [attr.stroke]="getScoreColor()" stroke-width="12"
              [attr.stroke-dasharray]="getArcLength()" stroke-dashoffset="0" stroke-linecap="round"
              class="transition-all duration-1000"/>
          </svg>
          <div class="absolute inset-0 flex flex-col items-center justify-center rotate-0">
            <span class="text-5xl font-bold text-white">{{ score?.score ?? '--' }}</span>
            <span class="text-slate-400 text-xs">out of 100</span>
          </div>
        </div>
        <span [class]="'px-4 py-1.5 rounded-full text-sm font-bold ' + getRiskBadge()">
          {{ score?.riskCategory ?? 'Not Analyzed' }} RISK
        </span>
        <button (click)="generateScore()" [disabled]="loading"
          class="mt-4 px-6 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white text-sm font-semibold rounded-xl transition-all">
          {{ loading ? 'Analyzing...' : '🔄 Regenerate Score' }}
        </button>
      </div>

      <!-- Dimension Scores -->
      <div class="col-span-2 bg-slate-900 border border-white/5 rounded-2xl p-6">
        <h3 class="text-white font-semibold mb-5">Scoring Dimensions</h3>
        <div class="space-y-4">
          <div *ngFor="let dim of dimensions">
            <div class="flex justify-between text-sm mb-1.5">
              <span class="text-slate-300 font-medium">{{ dim.name }}</span>
              <span class="text-white font-bold">{{ dim.value }}%</span>
            </div>
            <div class="h-2 bg-slate-800 rounded-full overflow-hidden">
              <div [style.width.%]="dim.value" [class]="'h-2 rounded-full transition-all duration-700 ' + dim.color"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Insights -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <!-- Positive Insights -->
      <div class="bg-slate-900 border border-emerald-500/10 rounded-2xl p-6">
        <div class="flex items-center gap-2 mb-4">
          <div class="w-8 h-8 bg-emerald-500/10 rounded-lg flex items-center justify-center">✅</div>
          <h3 class="text-white font-semibold">Positive Factors</h3>
        </div>
        <ul class="space-y-2">
          <li *ngFor="let insight of positiveInsights" class="flex items-start gap-2 text-sm text-slate-300">
            <span class="text-emerald-400 mt-0.5">•</span>
            {{ insight }}
          </li>
          <li *ngIf="positiveInsights.length === 0" class="text-slate-500 text-sm">Generate a score to see insights</li>
        </ul>
      </div>

      <!-- Risk Factors -->
      <div class="bg-slate-900 border border-red-500/10 rounded-2xl p-6">
        <div class="flex items-center gap-2 mb-4">
          <div class="w-8 h-8 bg-red-500/10 rounded-lg flex items-center justify-center">⚠️</div>
          <h3 class="text-white font-semibold">Risk Factors</h3>
        </div>
        <ul class="space-y-2">
          <li *ngFor="let risk of riskFactors" class="flex items-start gap-2 text-sm text-slate-300">
            <span class="text-red-400 mt-0.5">•</span>
            {{ risk }}
          </li>
          <li *ngIf="riskFactors.length === 0" class="text-slate-500 text-sm">Generate a score to see risk factors</li>
        </ul>
      </div>
    </div>
  </main>
</div>
  `
})
export class HealthScoreComponent implements OnInit {
  score: any = null;
  loading = false;
  positiveInsights: string[] = [];
  riskFactors: string[] = [];

  dimensions = [
    { name: 'Cash Flow Stability', value: 78, color: 'bg-blue-500' },
    { name: 'Revenue Growth', value: 85, color: 'bg-emerald-500' },
    { name: 'Payment Behaviour', value: 92, color: 'bg-indigo-500' },
    { name: 'Business Consistency', value: 70, color: 'bg-purple-500' },
    { name: 'Risk Factor', value: 65, color: 'bg-yellow-500' },
  ];

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.fetchScore();
  }

  fetchScore() {
    this.http.get<any>('/api/score/').subscribe({
      next: r => {
        this.score = r.data;
        if (this.score) {
          try { this.positiveInsights = JSON.parse(this.score.positiveInsightsJson || '[]'); } catch {}
          try { this.riskFactors = JSON.parse(this.score.riskFactorsJson || '[]'); } catch {}
        }
      },
      error: () => {}
    });
  }

  generateScore() {
    this.loading = true;
    this.http.post<any>('/api/score/generate', {}).subscribe({
      next: r => { this.score = r.data; this.loading = false; this.fetchScore(); },
      error: () => { this.loading = false; }
    });
  }

  getScoreColor(): string {
    const s = this.score?.score ?? 0;
    if (s >= 80) return '#10b981';
    if (s >= 60) return '#f59e0b';
    return '#ef4444';
  }

  getArcLength(): string {
    const circumference = 2 * Math.PI * 50;
    const pct = (this.score?.score ?? 0) / 100;
    return `${circumference * pct} ${circumference}`;
  }

  getRiskBadge(): string {
    const r = this.score?.riskCategory;
    if (r === 'LOW') return 'bg-emerald-500/20 text-emerald-400';
    if (r === 'MEDIUM') return 'bg-yellow-500/20 text-yellow-400';
    return 'bg-red-500/20 text-red-400';
  }
}
